#!/bin/sh

# Exit with usage instructions
exitUsage () {
  [ -n "$1" ] && printf "$0: $1\n\n" >&2
  cat <<-EOF >&2
	Usage: $0 [options]

	Options:
	 on  : sets up env for vpn
	 off : reverts env back to previous state before triggering vpn
	 loop : runs infinite loop to auto detect vpn, and will toggle on and off.
	EOF
  exit 2
}


auto_toggle(){
    if $(ip tuntap show | grep -w "tun0: tun" > /dev/null)
    then
        $0 on
    else
        $0 off
    fi
}

auto_toggle_loop(){
    while :
    do
        auto_toggle
    done
}

set_repos(){
    
    pushd /etc/yum.repos.d

    echo Setting up yum repos.......

    case $1 in
        "westpac")
            search='*.repo'
            regex='${file/$file/.$file}'
            move_file=Westpac-centos.repo
            proxy_mode='manual'

            for file in $search
            do 
                sudo mv "${file}" "${file/$file/.$file}";
            done

            sudo mv .Westpac-centos.repo Westpac-centos.repo
            ;;
        "normal")
            search='\.*.repo'
            cmd='sudo mv "$file" "${file/\./}";'
            regex='\./'
            move_file=Westpac-centos.repo
            proxy_mode='none'

            for file in $search
            do 
                sudo mv "${file}" "${file/\./}";
            done

            sudo mv Westpac-centos.repo .Westpac-centos.repo
            ;;
        *)
            exitUsage
    esac

    sudo yum -q clean all

    echo "Setting gnome proxy mode to $proxy_mode........."
    gsettings set org.gnome.system.proxy mode "'$proxy_mode'"
}

case $1 in
    "on")
        set_repos westpac
        ;;
    "off")
        set_repos normal
        ;;
    "")
        auto_toggle
        ;;
    "loop")
        auto_toggle_loop
        ;;
    *)
        exitUsage
        ;;
esac
