-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

-- Load in whatever is the current theme
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/current/theme/hyprland.conf — converted to hyprland.lua in the same dir.
-- Prepend the theme dir to package.path so require("hyprland") resolves the theme file,
-- not ./hyprland.lua (this file) which package.path's ./?.lua pattern would otherwise match.
package.path = os.getenv("HOME") .. "/.config/current/theme/?.lua;" .. package.path
require("hyprland")

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Key below
-- monitor = name, resolution, position, scale

-- Set up for home configuration, may need to change when on then move
hl.monitor({
    output = "desc:Dell Inc. DELL U2722DE 4P584H3",
    mode = "preferred",
    position = "0x0",
    scale = "auto",
})

hl.monitor({
    output = "desc:Iiyama North America PL2492H 12122307G1827",
    mode = "preferred",
    position = "2560x0",
    scale = "auto",
})

-- 6 Twomey Grove setup
hl.monitor({
    output = "desc:Lenovo Group Limited P27h-20 V90659RZ",
    mode = "preferred",
    position = "0x0",
    scale = "auto",
})

hl.monitor({
    output = "desc:Lenovo Group Limited LEN T27h-20 VNA4TYZ7",
    mode = "preferred",
    position = "2560x0",
    scale = "auto",
})

-- As suggested by arch wiki for scaling
-- https://wiki.archlinux.org/title/Framework_Laptop_13#HiDPI_settings
hl.monitor({
    output = "eDP-1",
    mode = "preferred",
    position = "1280x1440",
    scale = "1.566667",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:Dell Inc. DELL U2722DE 4P584H3",
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Dell Inc. DELL U2722DE 4P584H3",
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    monitor = "desc:Dell Inc. DELL U2722DE 4P584H3",
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    monitor = "desc:Dell Inc. DELL U2722DE 4P584H3",
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "desc:Iiyama North America PL2492H 12122307G1827",
    persistent = true,
})

hl.workspace_rule({
    workspace = "7",
    monitor = "desc:Dell Inc. DELL U2722DE 4P584H3",
    persistent = true,
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
local terminal = "uwsm app -- alacritty"
local fileManager = "uwsm app -- dolphin"
-- If your web app url contains #, type it as ## to prevent hyperland treat it as comments
-- As specified in https://github.com/Vladimir-csp/uwsm?tab=readme-ov-file#3-applications-and-slices
-- Using walker over wofi, as it is more feature rich
local menu = "walker"

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
-- This will make sure that xdg-desktop-portal-hyprland can get the required variables on startup.
-- exec-once = swaync

-- Launch all the web apps we want on startup, they need a little sleep,
-- otherwise they start on differrent workspaces
-- exec-once = [workspace 5 silent] bash -c "sleep 3; exec launch-webapp https://teams.microsoft.com.mcas.ms/v2/"

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- Using uwsm to set environment variables, so they are read from 
-- - ~/.config/uwsm/env
-- - ~/.config/uwsm/env-hyprland

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", mode = "allow" })

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.workspace_rule({
    workspace = "false",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + S", hl.dsp.layout("togglesplit, "))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + M", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "+1" })) end)
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("pkill waybar && uwsm app -- waybar &"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("CTRL + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + CTRL + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + CTRL + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + CTRL + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + CTRL + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + CTRL + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + CTRL + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + CTRL + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + CTRL + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + CTRL + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + CTRL + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + period", hl.dsp.layout("move +col"))
hl.bind(mainMod .. " + comma", hl.dsp.layout("swapcol l"))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("ALT + mouse:272", hl.dsp.window.drag())
hl.bind("ALT + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})

hl.window_rule({
    name = "ica-client-on-workspace-3",
    match = {
        class = "^(Wfica)$",
    },
    workspace = "3",
})

hl.window_rule({
    name = "brave-on-workspace-1",
    match = {
        class = "^brave-browser$",
    },
    workspace = "1",
})

hl.window_rule({
    name = "whatsapp-on-workspace-4",
    match = {
        class = "^brave-web.whatsapp.com__-Default$",
    },
    workspace = "4",
})

hl.window_rule({
    name = "messenger-on-workspace-4",
    match = {
        class = "^brave-messenger.com__-Default$",
    },
    workspace = "4",
})

hl.window_rule({
    name = "teams-on-workspace-5",
    match = {
        class = "^brave-teams.microsoft.com.mcas.ms__v2_-Default$",
    },
    workspace = "5",
})

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        -- layout = scrolling
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = "yes, please :)",
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
    -- "Smart gaps" / "No gaps when only"
    -- uncomment all if you wish to use that.
    -- workspace = w[tv1], gapsout:0, gapsin:0
    -- workspace = f[1], gapsout:0, gapsin:0
    -- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
    -- windowrule = rounding 0, floating:0, onworkspace:w[tv1]
    -- windowrule = bordersize 0, floating:0, onworkspace:f[1]
    -- windowrule = rounding 0, floating:0, onworkspace:f[1]
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        -- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
        initial_workspace_tracking = 2, -- This in is hope that webapps will create in the workspace they are triggered from
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#gestures
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- I don't really know how often I use this, but I'll leave it here
    -- Move focus with mainMod + arrow keys, I normally use vim-like hjkl below, so
    -- maybe I can remove this
    -- Move focus with mainMod + vim-like hjkl
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Need to use CTRL instead of SHIFT because of my custom keybinds
    -- Example special workspace (scratchpad)
    -- bind = $mainMod, S, togglespecialworkspace, magic
    -- bind = $mainMod SHIFT, S, movetoworkspace, special:magic
    -- Used on scrolling layout to move to the next column
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with ALT + LMB/RMB and dragging
    -- This is because I have only on SUPER key, which is on my right side, which is
    -- the same side as the mouse
    -- Laptop multimedia keys for volume and LCD brightness
    -- Requires playerctl
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- Ignore maximize requests from apps. You'll probably like this.
    -- Fix some dragging issues with XWayland
    -- Move ica client to workspace 3
    -- Move Brave to workspace 1
    -- Move whatsapp webapp to workspace 4
    -- Move messenger webapp to workspace 4
    -- Move teams webapp to workspace 5
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("/usr/lib/pam_kwallet_init")
    hl.exec_cmd("uwsm app -- elephant")
    hl.exec_cmd("uwsm app -- walker --gapplication-service")
    hl.exec_cmd("uwsm app -- waybar")
    hl.exec_cmd("uwsm app -- hypridle")
    hl.exec_cmd("uwsm app -- swaybg -i ~/.config/current/background -m fill")
    hl.exec_cmd("uwsm app -- mako")
    hl.exec_cmd("uwsm app -- handle-monitor-connect-hyprland")
    hl.exec_cmd("sudo ectool fwchargelimit 70")
    hl.exec_cmd("uwsm app -- brave", { workspace = "1 silent" })
    hl.exec_cmd(terminal, { workspace = "2 silent" })
    hl.exec_cmd("uwsm app -- keepassxc", { workspace = "7 silent" })
    hl.exec_cmd("bash -c \"sleep 3; exec launch-webapp https://web.whatsapp.com/\"", { workspace = "4 silent" })
    hl.exec_cmd("bash -c \"sleep 3; exec launch-webapp https://messenger.com/\"", { workspace = "4 silent" })
    hl.exec_cmd("bash -c \"sleep 3; exec uwsm app -- /opt/teams-for-linux/teams-for-linux --ozone-platform=wayland %U\"", { workspace = "5 silent" })
end)
