include ~/.config/current/theme/kitty.conf


# I want to be able to copy/paste like in other terminals
map ctrl+shift+c        copy_to_clipboard
map ctrl+shift+v        paste_from_clipboard

# Increase/decrease font size
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

font_size 18.0
